// This file was generated by counterfeiter
package fake_routing_table

import (
	"sync"

	"github.com/cloudfoundry-incubator/receptor"
	"github.com/cloudfoundry-incubator/route-emitter/routing_table"
)

type FakeRoutingTable struct {
	RouteCountStub        func() int
	routeCountMutex       sync.RWMutex
	routeCountArgsForCall []struct{}
	routeCountReturns     struct {
		result1 int
	}
	SwapStub        func(newTable routing_table.RoutingTable) routing_table.MessagesToEmit
	swapMutex       sync.RWMutex
	swapArgsForCall []struct {
		newTable routing_table.RoutingTable
	}
	swapReturns struct {
		result1 routing_table.MessagesToEmit
	}
	RemoveRoutesStub        func(key routing_table.RoutingKey, modTag receptor.ModificationTag) routing_table.MessagesToEmit
	removeRoutesMutex       sync.RWMutex
	removeRoutesArgsForCall []struct {
		key    routing_table.RoutingKey
		modTag receptor.ModificationTag
	}
	removeRoutesReturns struct {
		result1 routing_table.MessagesToEmit
	}
	SetRoutesFromDesiredStub        func(desiredLRP receptor.DesiredLRPResponse) routing_table.MessagesToEmit
	setRoutesFromDesiredMutex       sync.RWMutex
	setRoutesFromDesiredArgsForCall []struct {
		desiredLRP receptor.DesiredLRPResponse
	}
	setRoutesFromDesiredReturns struct {
		result1 routing_table.MessagesToEmit
	}
	UpdateRoutesFromDesiredStub        func(before, after receptor.DesiredLRPResponse) routing_table.MessagesToEmit
	updateRoutesFromDesiredMutex       sync.RWMutex
	updateRoutesFromDesiredArgsForCall []struct {
		before receptor.DesiredLRPResponse
		after  receptor.DesiredLRPResponse
	}
	updateRoutesFromDesiredReturns struct {
		result1 routing_table.MessagesToEmit
	}
	AddEndpointStub        func(key routing_table.RoutingKey, endpoint routing_table.Endpoint) routing_table.MessagesToEmit
	addEndpointMutex       sync.RWMutex
	addEndpointArgsForCall []struct {
		key      routing_table.RoutingKey
		endpoint routing_table.Endpoint
	}
	addEndpointReturns struct {
		result1 routing_table.MessagesToEmit
	}
	RemoveEndpointStub        func(key routing_table.RoutingKey, endpoint routing_table.Endpoint) routing_table.MessagesToEmit
	removeEndpointMutex       sync.RWMutex
	removeEndpointArgsForCall []struct {
		key      routing_table.RoutingKey
		endpoint routing_table.Endpoint
	}
	removeEndpointReturns struct {
		result1 routing_table.MessagesToEmit
	}
	AddEndpointFromActualStub        func(actualLRP receptor.ActualLRPResponse) routing_table.MessagesToEmit
	addEndpointFromActualMutex       sync.RWMutex
	addEndpointFromActualArgsForCall []struct {
		actualLRP receptor.ActualLRPResponse
	}
	addEndpointFromActualReturns struct {
		result1 routing_table.MessagesToEmit
	}
	MessagesToEmitStub        func() routing_table.MessagesToEmit
	messagesToEmitMutex       sync.RWMutex
	messagesToEmitArgsForCall []struct{}
	messagesToEmitReturns     struct {
		result1 routing_table.MessagesToEmit
	}
}

func (fake *FakeRoutingTable) RouteCount() int {
	fake.routeCountMutex.Lock()
	fake.routeCountArgsForCall = append(fake.routeCountArgsForCall, struct{}{})
	fake.routeCountMutex.Unlock()
	if fake.RouteCountStub != nil {
		return fake.RouteCountStub()
	} else {
		return fake.routeCountReturns.result1
	}
}

func (fake *FakeRoutingTable) RouteCountCallCount() int {
	fake.routeCountMutex.RLock()
	defer fake.routeCountMutex.RUnlock()
	return len(fake.routeCountArgsForCall)
}

func (fake *FakeRoutingTable) RouteCountReturns(result1 int) {
	fake.RouteCountStub = nil
	fake.routeCountReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeRoutingTable) Swap(newTable routing_table.RoutingTable) routing_table.MessagesToEmit {
	fake.swapMutex.Lock()
	fake.swapArgsForCall = append(fake.swapArgsForCall, struct {
		newTable routing_table.RoutingTable
	}{newTable})
	fake.swapMutex.Unlock()
	if fake.SwapStub != nil {
		return fake.SwapStub(newTable)
	} else {
		return fake.swapReturns.result1
	}
}

func (fake *FakeRoutingTable) SwapCallCount() int {
	fake.swapMutex.RLock()
	defer fake.swapMutex.RUnlock()
	return len(fake.swapArgsForCall)
}

func (fake *FakeRoutingTable) SwapArgsForCall(i int) routing_table.RoutingTable {
	fake.swapMutex.RLock()
	defer fake.swapMutex.RUnlock()
	return fake.swapArgsForCall[i].newTable
}

func (fake *FakeRoutingTable) SwapReturns(result1 routing_table.MessagesToEmit) {
	fake.SwapStub = nil
	fake.swapReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) RemoveRoutes(key routing_table.RoutingKey, modTag receptor.ModificationTag) routing_table.MessagesToEmit {
	fake.removeRoutesMutex.Lock()
	fake.removeRoutesArgsForCall = append(fake.removeRoutesArgsForCall, struct {
		key    routing_table.RoutingKey
		modTag receptor.ModificationTag
	}{key, modTag})
	fake.removeRoutesMutex.Unlock()
	if fake.RemoveRoutesStub != nil {
		return fake.RemoveRoutesStub(key, modTag)
	} else {
		return fake.removeRoutesReturns.result1
	}
}

func (fake *FakeRoutingTable) RemoveRoutesCallCount() int {
	fake.removeRoutesMutex.RLock()
	defer fake.removeRoutesMutex.RUnlock()
	return len(fake.removeRoutesArgsForCall)
}

func (fake *FakeRoutingTable) RemoveRoutesArgsForCall(i int) (routing_table.RoutingKey, receptor.ModificationTag) {
	fake.removeRoutesMutex.RLock()
	defer fake.removeRoutesMutex.RUnlock()
	return fake.removeRoutesArgsForCall[i].key, fake.removeRoutesArgsForCall[i].modTag
}

func (fake *FakeRoutingTable) RemoveRoutesReturns(result1 routing_table.MessagesToEmit) {
	fake.RemoveRoutesStub = nil
	fake.removeRoutesReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) SetRoutesFromDesired(desiredLRP receptor.DesiredLRPResponse) routing_table.MessagesToEmit {
	fake.setRoutesFromDesiredMutex.Lock()
	fake.setRoutesFromDesiredArgsForCall = append(fake.setRoutesFromDesiredArgsForCall, struct {
		desiredLRP receptor.DesiredLRPResponse
	}{desiredLRP})
	fake.setRoutesFromDesiredMutex.Unlock()
	if fake.SetRoutesFromDesiredStub != nil {
		return fake.SetRoutesFromDesiredStub(desiredLRP)
	} else {
		return fake.setRoutesFromDesiredReturns.result1
	}
}

func (fake *FakeRoutingTable) SetRoutesFromDesiredCallCount() int {
	fake.setRoutesFromDesiredMutex.RLock()
	defer fake.setRoutesFromDesiredMutex.RUnlock()
	return len(fake.setRoutesFromDesiredArgsForCall)
}

func (fake *FakeRoutingTable) SetRoutesFromDesiredArgsForCall(i int) receptor.DesiredLRPResponse {
	fake.setRoutesFromDesiredMutex.RLock()
	defer fake.setRoutesFromDesiredMutex.RUnlock()
	return fake.setRoutesFromDesiredArgsForCall[i].desiredLRP
}

func (fake *FakeRoutingTable) SetRoutesFromDesiredReturns(result1 routing_table.MessagesToEmit) {
	fake.SetRoutesFromDesiredStub = nil
	fake.setRoutesFromDesiredReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) UpdateRoutesFromDesired(before receptor.DesiredLRPResponse, after receptor.DesiredLRPResponse) routing_table.MessagesToEmit {
	fake.updateRoutesFromDesiredMutex.Lock()
	fake.updateRoutesFromDesiredArgsForCall = append(fake.updateRoutesFromDesiredArgsForCall, struct {
		before receptor.DesiredLRPResponse
		after  receptor.DesiredLRPResponse
	}{before, after})
	fake.updateRoutesFromDesiredMutex.Unlock()
	if fake.UpdateRoutesFromDesiredStub != nil {
		return fake.UpdateRoutesFromDesiredStub(before, after)
	} else {
		return fake.updateRoutesFromDesiredReturns.result1
	}
}

func (fake *FakeRoutingTable) UpdateRoutesFromDesiredCallCount() int {
	fake.updateRoutesFromDesiredMutex.RLock()
	defer fake.updateRoutesFromDesiredMutex.RUnlock()
	return len(fake.updateRoutesFromDesiredArgsForCall)
}

func (fake *FakeRoutingTable) UpdateRoutesFromDesiredArgsForCall(i int) (receptor.DesiredLRPResponse, receptor.DesiredLRPResponse) {
	fake.updateRoutesFromDesiredMutex.RLock()
	defer fake.updateRoutesFromDesiredMutex.RUnlock()
	return fake.updateRoutesFromDesiredArgsForCall[i].before, fake.updateRoutesFromDesiredArgsForCall[i].after
}

func (fake *FakeRoutingTable) UpdateRoutesFromDesiredReturns(result1 routing_table.MessagesToEmit) {
	fake.UpdateRoutesFromDesiredStub = nil
	fake.updateRoutesFromDesiredReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) AddEndpoint(key routing_table.RoutingKey, endpoint routing_table.Endpoint) routing_table.MessagesToEmit {
	fake.addEndpointMutex.Lock()
	fake.addEndpointArgsForCall = append(fake.addEndpointArgsForCall, struct {
		key      routing_table.RoutingKey
		endpoint routing_table.Endpoint
	}{key, endpoint})
	fake.addEndpointMutex.Unlock()
	if fake.AddEndpointStub != nil {
		return fake.AddEndpointStub(key, endpoint)
	} else {
		return fake.addEndpointReturns.result1
	}
}

func (fake *FakeRoutingTable) AddEndpointCallCount() int {
	fake.addEndpointMutex.RLock()
	defer fake.addEndpointMutex.RUnlock()
	return len(fake.addEndpointArgsForCall)
}

func (fake *FakeRoutingTable) AddEndpointArgsForCall(i int) (routing_table.RoutingKey, routing_table.Endpoint) {
	fake.addEndpointMutex.RLock()
	defer fake.addEndpointMutex.RUnlock()
	return fake.addEndpointArgsForCall[i].key, fake.addEndpointArgsForCall[i].endpoint
}

func (fake *FakeRoutingTable) AddEndpointReturns(result1 routing_table.MessagesToEmit) {
	fake.AddEndpointStub = nil
	fake.addEndpointReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) RemoveEndpoint(key routing_table.RoutingKey, endpoint routing_table.Endpoint) routing_table.MessagesToEmit {
	fake.removeEndpointMutex.Lock()
	fake.removeEndpointArgsForCall = append(fake.removeEndpointArgsForCall, struct {
		key      routing_table.RoutingKey
		endpoint routing_table.Endpoint
	}{key, endpoint})
	fake.removeEndpointMutex.Unlock()
	if fake.RemoveEndpointStub != nil {
		return fake.RemoveEndpointStub(key, endpoint)
	} else {
		return fake.removeEndpointReturns.result1
	}
}

func (fake *FakeRoutingTable) RemoveEndpointCallCount() int {
	fake.removeEndpointMutex.RLock()
	defer fake.removeEndpointMutex.RUnlock()
	return len(fake.removeEndpointArgsForCall)
}

func (fake *FakeRoutingTable) RemoveEndpointArgsForCall(i int) (routing_table.RoutingKey, routing_table.Endpoint) {
	fake.removeEndpointMutex.RLock()
	defer fake.removeEndpointMutex.RUnlock()
	return fake.removeEndpointArgsForCall[i].key, fake.removeEndpointArgsForCall[i].endpoint
}

func (fake *FakeRoutingTable) RemoveEndpointReturns(result1 routing_table.MessagesToEmit) {
	fake.RemoveEndpointStub = nil
	fake.removeEndpointReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) AddEndpointFromActual(actualLRP receptor.ActualLRPResponse) routing_table.MessagesToEmit {
	fake.addEndpointFromActualMutex.Lock()
	fake.addEndpointFromActualArgsForCall = append(fake.addEndpointFromActualArgsForCall, struct {
		actualLRP receptor.ActualLRPResponse
	}{actualLRP})
	fake.addEndpointFromActualMutex.Unlock()
	if fake.AddEndpointFromActualStub != nil {
		return fake.AddEndpointFromActualStub(actualLRP)
	} else {
		return fake.addEndpointFromActualReturns.result1
	}
}

func (fake *FakeRoutingTable) AddEndpointFromActualCallCount() int {
	fake.addEndpointFromActualMutex.RLock()
	defer fake.addEndpointFromActualMutex.RUnlock()
	return len(fake.addEndpointFromActualArgsForCall)
}

func (fake *FakeRoutingTable) AddEndpointFromActualArgsForCall(i int) receptor.ActualLRPResponse {
	fake.addEndpointFromActualMutex.RLock()
	defer fake.addEndpointFromActualMutex.RUnlock()
	return fake.addEndpointFromActualArgsForCall[i].actualLRP
}

func (fake *FakeRoutingTable) AddEndpointFromActualReturns(result1 routing_table.MessagesToEmit) {
	fake.AddEndpointFromActualStub = nil
	fake.addEndpointFromActualReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) MessagesToEmit() routing_table.MessagesToEmit {
	fake.messagesToEmitMutex.Lock()
	fake.messagesToEmitArgsForCall = append(fake.messagesToEmitArgsForCall, struct{}{})
	fake.messagesToEmitMutex.Unlock()
	if fake.MessagesToEmitStub != nil {
		return fake.MessagesToEmitStub()
	} else {
		return fake.messagesToEmitReturns.result1
	}
}

func (fake *FakeRoutingTable) MessagesToEmitCallCount() int {
	fake.messagesToEmitMutex.RLock()
	defer fake.messagesToEmitMutex.RUnlock()
	return len(fake.messagesToEmitArgsForCall)
}

func (fake *FakeRoutingTable) MessagesToEmitReturns(result1 routing_table.MessagesToEmit) {
	fake.MessagesToEmitStub = nil
	fake.messagesToEmitReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

var _ routing_table.RoutingTable = new(FakeRoutingTable)
